// frontend/web/src/pages/login/components/organisms/form-login.tsx
import { component$ } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { Button, Input, Title } from '@ui/components';
import { handleInput } from '../../../../hooks';
import { useLogin } from '../../hooks/useLogin';

export const FormLogin = component$(() => {
  const {
    formLogin,
    emailError,
    emailTouched,
    isFormValid,
    passwordError,
    passwordTouched,
  } = useLogin();
  return (
    <>
      <Title style="title-2xl">Login Form</Title>
      <div class="w-full flex flex-col gap-4">
        <div class="relative">
          <Input
            value={formLogin.email}
            errors={emailTouched.value ? emailError.value : ''}
            name="email"
            type="text"
            placeholder="Email Address"
            titleLabel="Email Address"
            style="input-primary"
            onInput$={(e) => handleInput(e, formLogin, 'email')}
            onBlur$={() => (emailTouched.value = true)}
          />
        </div>
        <div class="relative">
          <Input
            value={formLogin.password}
            errors={passwordTouched.value ? passwordError.value : ''}
            name="password"
            type="password"
            placeholder="Password"
            titleLabel="Password"
            style="input-primary"
            onInput$={(e) => handleInput(e, formLogin, 'password')}
            onBlur$={() => (passwordTouched.value = true)}
          />
        </div>
        <Link class="underline" href="/recover">
          have you forgotten your password ?
        </Link>
      </div>
      <div class="relative w-full">
        <Button
          style="button-primary"
          color="t-white"
          type="submit"
          disabled={!isFormValid.value}
        >
          Login
        </Button>
      </div>
    </>
  );
});

// frontend/app/src/auth/components/organisms/form-login/form-login.component.ts
import { Component, OnInit, inject } from '@angular/core';
import {
  FormBuilder,
  FormControl,
  FormGroup,
  Validators,
} from '@angular/forms';
import { BehaviorSubject, Subscription } from 'rxjs';
import { ValidatorsService } from '../../../../utils';

@Component({
  selector: 'form-login',
  templateUrl: './form-login.component.html',
  styleUrls: ['./form-login.component.scss'],
})
export class FormLoginComponent implements OnInit {
  private formBuilder = inject(FormBuilder);
  private validatorsService = inject(ValidatorsService);

  private passwordSubscription?: Subscription;
  private passwordSource = new BehaviorSubject<string | null>(null);
  labelEmail = 'Email';
  labelPassword = 'Password';
  formLogin!: FormGroup;
  password$ = this.passwordSource.asObservable();

  get emailControl(): FormControl {
    return this.formLogin.get('email') as FormControl;
  }

  ngOnInit(): void {
    this.formLogin = this.formBuilder.group({
      email: ['', Validators.required],
      password: [
        '',
        [
          Validators.required,
          Validators.minLength(6),
          Validators.maxLength(50),
        ],
      ],
    });

    this.passwordSubscription = this.password$.subscribe((pass) => {
      const control = this.formLogin.get('password');
      if (control) {
        control.setValidators([
          Validators.required,
          Validators.minLength(6),
          Validators.maxLength(50),
          this.validatorsService.similarInputs(pass!, 'password'),
        ]);
        control.updateValueAndValidity();
      }
    });
  }

  ngOnDestroy(): void {
    this.passwordSubscription?.unsubscribe();
  }
}

<div class="flex flex-col justify-center gap-4 items-center">
  <c-title css="title-2xl">Login Form</c-title>
  <div class="w-full flex flex-col gap-4">
    <div class="relative">
      <c-label>
        {{ labelEmail }}
        <c-input
          css="input-primary"
          type="text"
          placeholder="jhonDoe@example.com"
          [formControl]="emailControl"
          name="email"
        />
      </c-label>
    </div>
    <div class="relative">
      <c-label>
        {{ labelPassword }}
        <c-input
          css="input-primary"
          type="password"
          placeholder="*******"
          [formControl]="emailControl"
          name="password"
        />
      </c-label>
    </div>
    <a class="underline" href="/recover">
      have you forgotten your password ?
    </a>
  </div>
  <div class="relative w-full">
    <c-button class="w-full" css="button-primary" color="t-white" type="submit">
      <c-title css="title-base">Login</c-title>
    </c-button>
  </div>
</div>
