// frontend/app/src/pages/auth/components/organisms/form-recover/form-recover.component.ts
import { Component, OnInit, inject } from '@angular/core';
import {
  FormBuilder,
  FormControl,
  FormGroup,
  Validators,
} from '@angular/forms';

@Component({
  selector: 'form-recover',
  templateUrl: './form-recover.component.html',
  styleUrls: ['./form-recover.component.scss'],
})
export class FormRecoverComponent implements OnInit {
  private formBuilder = inject(FormBuilder);

  formRegister!: FormGroup;

  get emailControl(): FormControl {
    return this.formRegister.get('email') as FormControl;
  }

  ngOnInit(): void {
    this.formRegister = this.formBuilder.group({
      email: ['', Validators.required],
    });
  }
}

<div class="flex flex-col justify-center gap-4 items-center">
  <c-title css="title-2xl">Recover password</c-title>
  <div class="relative">
    <c-label>
      Email
      <c-input
        css="input-primary"
        type="email"
        placeholder="jhonDoe@example.com"
        [formControl]="emailControl"
        name="email"
      />
    </c-label>
  </div>
  <div class="relative w-full">
    <c-button
      [disabled]="!formRegister.value"
      class="w-full"
      css="button-primary"
      color="t-white"
      type="submit"
    >
      <c-title css="title-base">Send</c-title>
    </c-button>
  </div>
</div>

// frontend/web/src/pages/login/components/organisms/form-recover.tsx
import { component$ } from '@builder.io/qwik';
import { Button, Input, Title } from '@ui/components';
import { handleInput } from '../../../../hooks';
import { useRecover } from '../../hooks';

export const FormRecover = component$(() => {
  const { formRecover, emailError, emailTouched, isFormValid } = useRecover();
  return (
    <>
      <Title style="title-2xl">Recover password</Title>
      <div class="w-full flex flex-col gap-4">
        <div class="relative">
          <Input
            value={formRecover.email}
            errors={emailTouched.value ? emailError.value : ''}
            name="email"
            type="text"
            placeholder="Email Address"
            titleLabel="Email Address"
            style="input-primary"
            onInput$={(e) => handleInput(e, formRecover, 'email')}
            onBlur$={() => (emailTouched.value = true)}
          />
        </div>
      </div>
      <div class="relative w-full">
        <Button
          style="button-primary"
          color="t-white"
          type="submit"
          disabled={!isFormValid.value}
        >
          Enviar
        </Button>
      </div>
    </>
  );
});
