// frontend/app/src/pages/auth/components/organisms/form-login/form-login.component.ts
import { Component, OnInit, inject } from '@angular/core';
import {
  FormBuilder,
  FormControl,
  FormGroup,
  Validators,
} from '@angular/forms';
import { InputType } from '@ui/components';
import { LoginStateService } from '../../../service/state';

@Component({
  selector: 'form-login',
  templateUrl: './form-login.component.html',
  styleUrls: ['./form-login.component.scss'],
})
export class FormLoginComponent implements OnInit {
  private formBuilder = inject(FormBuilder);
  private loginService = inject(LoginStateService);
  type!: InputType['type'];

  formRegister!: FormGroup;

  get emailControl(): FormControl {
    return this.formRegister.get('email') as FormControl;
  }

  get passwordControl(): FormControl {
    return this.formRegister.get('password') as FormControl;
  }

  ngOnInit(): void {
    this.formRegister = this.formBuilder.group({
      email: ['', Validators.required],
      password: [
        '',
        [
          Validators.required,
          Validators.minLength(6),
          Validators.maxLength(50),
        ],
      ],
    });
  }

  onSubmit() {
    if (!this.formRegister.valid) return;

    this.loginService.onSubmit(this.formRegister);
  }
}

<form
  [formGroup]="formRegister"
  (ngSubmit)="onSubmit()"
  class="w-full flex flex-col gap-6 items-center"
>
  <div class="flex flex-col justify-center gap-4 items-center">
    <c-title css="title-2xl">Login</c-title>
    <div class="w-full flex flex-col gap-4">
      <div class="relative">
        <c-label>
          Email
          <c-input
            css="input-primary"
            type="email"
            placeholder="jhonDoe@example.com"
            [formControl]="emailControl"
            name="email"
            [additionalValidators]="emailValidators"
          />
        </c-label>
      </div>
      <div class="relative">
        <c-label>
          Pasword
          <c-input
            css="input-primary"
            type="password"
            placeholder="*******"
            [formControl]="passwordControl"
            name="password"
          />
        </c-label>
      </div>
      <a class="underline" routerLink="/auth/recover">
        have you forgotten your password ?
      </a>
    </div>
    <div class="relative w-full">
      <c-button
        class="w-full"
        css="button-primary"
        color="t-white"
        type="submit"
        [disabled]="!formRegister.valid"
      >
        <c-title css="title-base">Login</c-title>
      </c-button>
    </div>
  </div>
</form>

// frontend/web/src/pages/login/components/organisms/form-login.tsx
import { component$ } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { Button, Input, Title } from '@ui/components';
import { handleInput } from '../../../../hooks';
import { useLogin } from '../../hooks/useLogin';

export const FormLogin = component$(() => {
  const {
    formLogin,
    emailError,
    emailTouched,
    isFormValid,
    passwordError,
    passwordTouched,
  } = useLogin();
  return (
    <>
      <Title style="title-2xl">Login Form</Title>
      <div class="w-full flex flex-col gap-4">
        <div class="relative">
          <Input
            value={formLogin.email}
            errors={emailTouched.value ? emailError.value : ''}
            name="email"
            type="text"
            placeholder="Email Address"
            titleLabel="Email Address"
            style="input-primary"
            onInput$={(e) => handleInput(e, formLogin, 'email')}
            onBlur$={() => (emailTouched.value = true)}
          />
        </div>
        <div class="relative">
          <Input
            value={formLogin.password}
            errors={passwordTouched.value ? passwordError.value : ''}
            name="password"
            type="password"
            placeholder="Password"
            titleLabel="Password"
            style="input-primary"
            onInput$={(e) => handleInput(e, formLogin, 'password')}
            onBlur$={() => (passwordTouched.value = true)}
          />
        </div>
        <Link class="underline" href="/recover">
          have you forgotten your password ?
        </Link>
      </div>
      <div class="relative w-full">
        <Button
          style="button-primary"
          color="t-white"
          type="submit"
          disabled={!isFormValid.value}
        >
          Login
        </Button>
      </div>
    </>
  );
});
