// frontend/app/src/pages/auth/components/organisms/form-register/form-register.component.ts
import { Component, OnInit, inject } from '@angular/core';
import {
  FormBuilder,
  FormControl,
  FormGroup,
  Validators,
} from '@angular/forms';
import { BehaviorSubject } from 'rxjs';

@Component({
  selector: 'form-register',
  templateUrl: './form-register.component.html',
  styleUrls: ['./form-register.component.scss'],
})
export class FormRegisterComponent implements OnInit {
  private formBuilder = inject(FormBuilder);

  private passwordSource = new BehaviorSubject<string | null>(null);
  formRegister!: FormGroup;
  password$ = this.passwordSource.asObservable();

  get emailControl(): FormControl {
    return this.formRegister.get('email') as FormControl;
  }

  get usernameControl(): FormControl {
    return this.formRegister.get('username') as FormControl;
  }

  get passwordControl(): FormControl {
    return this.formRegister.get('password') as FormControl;
  }

  ngOnInit(): void {
    this.formRegister = this.formBuilder.group({
      email: ['', Validators.required],
      username: ['', Validators.required],
      password: [
        '',
        [
          Validators.required,
          Validators.minLength(6),
          Validators.maxLength(50),
        ],
      ],
    });
  }
}

<div class="flex flex-col justify-center gap-4 items-center">
  <c-title css="title-2xl">Register</c-title>
  <div class="w-full flex flex-col gap-4">
    <div class="relative">
      <c-label>
        Email
        <c-input
          css="input-primary"
          type="email"
          placeholder="jhonDoe@example.com"
          [formControl]="emailControl"
          name="email"
        />
      </c-label>
    </div>
    <div class="relative">
      <c-label>
        Username
        <c-input
          css="input-primary"
          type="text"
          placeholder="Jhon Doe"
          [formControl]="usernameControl"
          name="username"
        />
      </c-label>
    </div>
    <div class="relative">
      <c-label>
        Password
        <c-input
          css="input-primary"
          type="password"
          placeholder="*******"
          [formControl]="passwordControl"
          name="password"
        />
      </c-label>
    </div>
  </div>
  <div class="relative w-full">
    <c-button
      [disabled]="!formRegister.value"
      class="w-full"
      css="button-primary"
      color="t-white"
      type="submit"
    >
      <c-title css="title-base">Sign in</c-title>
    </c-button>
  </div>
</div>

// frontend/web/src/pages/login/components/organisms/form-register.tsx
import { component$ } from '@builder.io/qwik';
import { Button, Input, Title } from '@ui/components';
import { handleInput } from '../../../../hooks';
import { useRegister } from '../../hooks/useRegister';

export const FormRegister = component$(() => {
  const {
    formRegister,
    emailError,
    emailTouched,
    isFormValid,
    passwordError,
    passwordTouched,
    usernameError,
    usernameTouched,
  } = useRegister();
  return (
    <>
      <Title style="title-2xl">Register Form</Title>
      <div class="w-full flex flex-col gap-4">
        <div class="relative">
          <Input
            value={formRegister.email}
            errors={emailTouched.value ? emailError.value : ''}
            name="email"
            type="text"
            placeholder="Email Address"
            titleLabel="Email Address"
            style="input-primary"
            onInput$={(e) => handleInput(e, formRegister, 'email')}
            onBlur$={() => (emailTouched.value = true)}
          />
        </div>
        <div class="relative">
          <Input
            value={formRegister.username}
            errors={usernameTouched.value ? usernameError.value : ''}
            name="username"
            type="text"
            placeholder="Enter your username"
            titleLabel="Username"
            style="input-primary"
            onInput$={(e) => handleInput(e, formRegister, 'username')}
            onBlur$={() => (usernameTouched.value = true)}
          />
        </div>
        <div class="relative">
          <Input
            value={formRegister.password}
            errors={passwordTouched.value ? passwordError.value : ''}
            name="password"
            type="password"
            placeholder="Enter your password"
            titleLabel="Password"
            style="input-primary"
            onInput$={(e) => handleInput(e, formRegister, 'password')}
            onBlur$={() => (passwordTouched.value = true)}
          />
        </div>
      </div>
      <div class="relative w-full">
        <Button
          style="button-primary"
          color="t-white"
          type="submit"
          disabled={!isFormValid.value}
        >
          Sign in
        </Button>
      </div>
    </>
  );
});
